version: '3.9'
services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
    container_name: react-app
    stdin_open: true
    volumes:
       - ./react-app:/app
       - /app/node_modules