version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 420995033334.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t react-app ./react-app
      - docker tag react-app:latest 420995033334.dkr.ecr.eu-west-1.amazonaws.com/react-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 420995033334.dkr.ecr.eu-west-1.amazonaws.com/react-app:latest