apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.microname }}
  name: {{ .Values.microname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.microname }}
  template:
    metadata:
      labels:
        app: {{ .Values.microname }}
    spec:
      containers:
      - image: {{ .Values.registry }}/{{ .Values.microname }}:{{ .Values.build_id }}
        name: {{ .Values.microname }}
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true